### ISSUE TITLE
Error: "Hit enter key to step optimization!"  when launching trajopt_examples

### ISSUE THREAD

**Issue by hmz-15** [ros-industrial-consortium/trajopt_ros#66]
I have just built the packages and dependencies, and tried the examples in package "trajopt_examples". However, whichever launch file I used, the same error came out:

[ERROR] [1547913499.813080944]: Hit enter key to step optimization!

It seems that I didn't even get into the main function. It seems to be a quite simple problem, but I really can't find a way to deal with it. I appreciate it a lot for your help.

**Comment by Levi-Armstrong** [comment]
Set the launch parameter plotting equal to false.

**Comment by Levi-Armstrong** [comment]
`<arg name="plotting" default="true"/>`

**Comment by mpowelson** [comment]
Just to clarify, the previous "error" is not actually an error. When you select plotting = true the optimization steps through each iteration one at a time so that you can see it. It is an error message simply so that it will be red, and you will notice it.

The second error is discussed in #56 . That actually is an error but it occurs after the path planning has occurred. It shouldn't effect you using it. Hang in there with these examples. It's on our to do list to clean these up, and we have a full tutorial in the works to add to the ROS-I training material soon.

**Comment by aykutonol** [comment]
I had the exact same issue and resolved it by (re)installing libglfw by `sudo apt install libglfw3-dev libglfw3`. I hope that helps!

**Comment by mpowelson** [comment]
The training mentioned above was published on the industrial training page. Find it here
https://industrial-training-master.readthedocs.io/en/melodic/_source/demo3/index.html


I believe the library unloader issue has been resolved as well now. However if you are still having issues, feel free to reopen this
